"use server";
import { revalidatePath } from "next/cache";
import { requireCurrentWorkspace } from "../../../src/auth/current-workspace";
import { recordAuditEvent } from "../../../src/application/audit/audit-service";
import {createPriceLevel,createDiscountRule,createInstallmentPlan,createCommissionRule,createCurrencyRate,setCatalogBarcode} from "../../../src/application/commercial/commercial-config-service";
const t=(f:FormData,k:string)=>String(f.get(k)??"");const n=(f:FormData,k:string)=>Number.parseInt(t(f,k),10);const b=(f:FormData,k:string)=>BigInt(t(f,k)||"0");
async function ctx(){const c=await requireCurrentWorkspace();if(c.role==="VIEWER")throw new Error("COMMERCIAL_PERMISSION_DENIED");return c}
async function audit(c:Awaited<ReturnType<typeof ctx>>,action:string,type:string,id:string){await recordAuditEvent({workspaceId:c.workspace.id,actorId:c.userId,actorRole:c.role,action,category:"COMMERCIAL",entityType:type,entityId:id})}
export async function createPriceLevelAction(f:FormData){const c=await ctx();const x=await createPriceLevel({workspaceId:c.workspace.id,code:t(f,"code"),name:t(f,"name"),multiplierBasisPoints:n(f,"multiplierBasisPoints")});await audit(c,"PRICE_LEVEL_CREATED","CommercialPriceLevel",x.id);revalidatePath("/app/commercial-controls")}
export async function createDiscountRuleAction(f:FormData){const c=await ctx();const x=await createDiscountRule({workspaceId:c.workspace.id,code:t(f,"code"),name:t(f,"name"),percentageBasisPoints:n(f,"percentageBasisPoints"),fixedAmount:b(f,"fixedAmount"),minimumPurchase:b(f,"minimumPurchase")});await audit(c,"DISCOUNT_RULE_CREATED","CommercialDiscountRule",x.id);revalidatePath("/app/commercial-controls")}
export async function createInstallmentPlanAction(f:FormData){const c=await ctx();const x=await createInstallmentPlan({workspaceId:c.workspace.id,code:t(f,"code"),name:t(f,"name"),installmentCount:n(f,"installmentCount"),firstDueDays:n(f,"firstDueDays"),intervalDays:n(f,"intervalDays"),markupBasisPoints:n(f,"markupBasisPoints")});await audit(c,"INSTALLMENT_PLAN_CREATED","InstallmentPlan",x.id);revalidatePath("/app/commercial-controls")}
export async function createCommissionRuleAction(f:FormData){const c=await ctx();const x=await createCommissionRule({workspaceId:c.workspace.id,code:t(f,"code"),name:t(f,"name"),rateBasisPoints:n(f,"rateBasisPoints"),basis:t(f,"basis")});await audit(c,"COMMISSION_RULE_CREATED","CommissionRule",x.id);revalidatePath("/app/commercial-controls")}
export async function createCurrencyRateAction(f:FormData){const c=await ctx();const x=await createCurrencyRate({workspaceId:c.workspace.id,currency:t(f,"currency"),rateToIrr:b(f,"rateToIrr"),effectiveAt:new Date(t(f,"effectiveAt"))});await audit(c,"CURRENCY_RATE_CREATED","CurrencyRate",x.id);revalidatePath("/app/commercial-controls")}
export async function setBarcodeAction(f:FormData){const c=await ctx();const id=t(f,"itemId");await setCatalogBarcode({workspaceId:c.workspace.id,itemId:id,barcode:t(f,"barcode")});await audit(c,"CATALOG_BARCODE_UPDATED","CatalogItem",id);revalidatePath("/app/commercial-controls")}
