import { prisma } from "../../lib/prisma";
import { assertWorkspaceWriteEntitlement } from "../subscription/workspace-entitlement";
const normCode=(v:string)=>{const x=v.trim().toUpperCase();if(!/^[A-Z0-9_-]{1,40}$/.test(x))throw new Error("COMMERCIAL_CODE_INVALID");return x};
const normName=(v:string)=>{const x=v.trim();if(x.length<2||x.length>120)throw new Error("COMMERCIAL_NAME_INVALID");return x};
const bps=(v:number,max=100000)=>{if(!Number.isInteger(v)||v<0||v>max)throw new Error("COMMERCIAL_BPS_INVALID");return v};
export async function listCommercialConfig(workspaceId:string){const [priceLevels,discountRules,installmentPlans,commissionRules,currencyRates]=await Promise.all([prisma.commercialPriceLevel.findMany({where:{workspaceId}}),prisma.commercialDiscountRule.findMany({where:{workspaceId}}),prisma.installmentPlan.findMany({where:{workspaceId}}),prisma.commissionRule.findMany({where:{workspaceId}}),prisma.currencyRate.findMany({where:{workspaceId},orderBy:{effectiveAt:"desc"}})]);return{priceLevels,discountRules,installmentPlans,commissionRules,currencyRates}}
export async function createPriceLevel(i:{workspaceId:string;code:string;name:string;multiplierBasisPoints:number}){await assertWorkspaceWriteEntitlement(i.workspaceId);return prisma.commercialPriceLevel.create({data:{workspaceId:i.workspaceId,code:normCode(i.code),name:normName(i.name),multiplierBasisPoints:bps(i.multiplierBasisPoints,50000)}})}
export async function createDiscountRule(i:{workspaceId:string;code:string;name:string;percentageBasisPoints:number;fixedAmount:bigint;minimumPurchase:bigint}){await assertWorkspaceWriteEntitlement(i.workspaceId);if(i.fixedAmount<0n||i.minimumPurchase<0n)throw new Error("COMMERCIAL_AMOUNT_INVALID");return prisma.commercialDiscountRule.create({data:{workspaceId:i.workspaceId,code:normCode(i.code),name:normName(i.name),percentageBasisPoints:bps(i.percentageBasisPoints,10000),fixedAmount:i.fixedAmount,minimumPurchase:i.minimumPurchase}})}
export async function createInstallmentPlan(i:{workspaceId:string;code:string;name:string;installmentCount:number;firstDueDays:number;intervalDays:number;markupBasisPoints:number}){await assertWorkspaceWriteEntitlement(i.workspaceId);if(!Number.isInteger(i.installmentCount)||i.installmentCount<1||i.installmentCount>120||!Number.isInteger(i.firstDueDays)||i.firstDueDays<0||!Number.isInteger(i.intervalDays)||i.intervalDays<1)throw new Error("INSTALLMENT_INVALID");return prisma.installmentPlan.create({data:{...i,code:normCode(i.code),name:normName(i.name),markupBasisPoints:bps(i.markupBasisPoints)}})}
export async function createCommissionRule(i:{workspaceId:string;code:string;name:string;rateBasisPoints:number;basis:string}){await assertWorkspaceWriteEntitlement(i.workspaceId);return prisma.commissionRule.create({data:{workspaceId:i.workspaceId,code:normCode(i.code),name:normName(i.name),rateBasisPoints:bps(i.rateBasisPoints,10000),basis:i.basis==="GROSS"?"GROSS":"NET_AFTER_DISCOUNT"}})}
export async function createCurrencyRate(i:{workspaceId:string;currency:string;rateToIrr:bigint;effectiveAt:Date}){await assertWorkspaceWriteEntitlement(i.workspaceId);const currency=i.currency.trim().toUpperCase();if(!/^[A-Z]{3}$/.test(currency)||currency==="IRR"||i.rateToIrr<=0n||Number.isNaN(i.effectiveAt.getTime()))throw new Error("CURRENCY_RATE_INVALID");return prisma.currencyRate.create({data:{workspaceId:i.workspaceId,currency,rateToIrr:i.rateToIrr,effectiveAt:i.effectiveAt}})}
export async function setCatalogBarcode(i:{workspaceId:string;itemId:string;barcode:string|null}){await assertWorkspaceWriteEntitlement(i.workspaceId);const barcode=i.barcode?.trim()||null;if(barcode&&!/^[A-Za-z0-9._-]{4,64}$/.test(barcode))throw new Error("BARCODE_INVALID");if(barcode&&await prisma.catalogItem.findFirst({where:{workspaceId:i.workspaceId,barcode,NOT:{id:i.itemId}},select:{id:true}}))throw new Error("BARCODE_DUPLICATE");const r=await prisma.catalogItem.updateMany({where:{id:i.itemId,workspaceId:i.workspaceId},data:{barcode}});if(r.count!==1)throw new Error("CATALOG_ITEM_NOT_FOUND")}
